
CREATE TABLE IF NOT EXISTS BILL(
	BILL_ID INT,
    INTIAL_COST DECIMAL(2,2),
    FORM_ID INT NOT NULL,
    PRIMARY KEY (BILL_ID),
    FOREIGN KEY (FORM_ID) REFERENCES FORM(FORM_ID)
);

CREATE TABLE IF NOT EXISTS DEPARTMENT (
    DNO INT,
    DNAME VARCHAR(255) UNIQUE NOT NULL,
    PRIMARY KEY (DNO)
);


CREATE TABLE IF NOT EXISTS DIAGNOSIS(
	DIAGNOSIS_ID INT,
    ICDIOCM VARCHAR(7),
    D_NAME VARCHAR(255),
    FORM_ID INT NOT NULL,
    SERVICE_EMPLOYEE_ID INT NOT NULL,
    PRIMARY KEY (DIAGNOSIS_ID),
    FOREIGN KEY (FORM_ID) REFERENCES FORM(FORM_ID),
    FOREIGN KEY (SERVICE_EMPLOYEE_ID) REFERENCES SERVICE_PROVIDER(SERVICE_EMPLOYEE_ID)
);

CREATE TABLE IF NOT EXISTS EMERGENCY_CONTACT (
    EMERGENCY_ID INT,
    FNAME VARCHAR(255),
    MNAME VARCHAR(255),
    LNAME VARCHAR(255),
    PRIMARY KEY (EMERGENCY_ID)
);

CREATE TABLE IF NOT EXISTS EMERGENCY_PHONE_NUMBERS(
	EMERGENCY_ID INT,
    PHONE_NUMBER VARCHAR(25),
    PRIMARY KEY (EMERGENCY_ID, PHONE_NUMBER),
    FOREIGN KEY (EMERGENCY_ID) REFERENCES EMERGENCY_CONTACT(EMERGENCY_ID)
);

CREATE TABLE IF NOT EXISTS FORM (
    FORM_ID INT,
    F_DATE DATETIME,
    CLERK_ID INT NOT NULL,
    PRIMARY KEY (FORM_ID),
    FOREIGN KEY (CLERK_ID) REFERENCES INTAKE_CLERK(INTAKE_EMPLOYEE_ID)
);

CREATE TABLE IF NOT EXISTS GUARDIAN (
    GUARDIAN_ID INT,
    FNAME VARCHAR(255),
    MNAME VARCHAR(255),
    LNAME VARCHAR(255),
    PRIMARY KEY (GUARDIAN_ID)
);

CREATE TABLE IF NOT EXISTS INITIAL_ASSESSMENT_MEDICATION(
	MED_ID INT,
    ASSESSMENT_ID INT,
    I_NAME VARCHAR(255),
    PRIMARY KEY (MED_ID, ASSESSMENT_ID),
    FOREIGN KEY (MED_ID) REFERENCES MEDICATION(MED_ID),
    FOREIGN KEY (ASSESSMENT_ID) REFERENCES INITIAL_ASSESSMENT(ASSESSMENT_ID)
);

CREATE TABLE IF NOT EXISTS INITIAL_VISIT(
	INTAKE_EMPLOYEE_ID INT NOT NULL,
    FORM_ID INT,
    PATIENT_ID INT,
    PRIMARY KEY (PATIENT_ID, FORM_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
    FOREIGN KEY (FORM_ID) REFERENCES FORM(FORM_ID),
    FOREIGN KEY (INTAKE_EMPLOYEE_ID) REFERENCES INTAKE_CLERK(INTAKE_EMPLOYEE_ID)
);

CREATE TABLE IF NOT EXISTS INSURANCE_PROVIDER (
    MEMBER_ID INT,
    POLICY_NUMBER VARCHAR(255),
    START_DATE DATE,
    END_DATE DATE,
    PATIENT_ID INT NOT NULL,
    PRIMARY KEY (MEMBER_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);


CREATE TABLE IF NOT EXISTS INTAKE_CLERK(
	INTAKE_EMPLOYEE_ID INT,
    FNAME VARCHAR(255),
    MNAME VARCHAR(255),
    LNAME VARCHAR(255),
    PAYSCALE DECIMAL(2,2),
    SALARY DECIMAL(2,2),
    DNO INT NOT NULL,
    PRIMARY KEY (INTAKE_EMPLOYEE_ID),
    FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNO)
);

CREATE TABLE IF NOT EXISTS INITIAL_ASSESSMENT (
    ASSESSMENT_ID INT,
    HEIGHT VARCHAR(255),
    WEIGHT DECIMAL(2,2),
    BLOOD_PRESSURE VARCHAR(255),
    TEMPERATURE DECIMAL(2,2),
    FORM_ID INT NOT NULL,
    NURSE_EMPLOYEE_ID INT NOT NULL,
    PRIMARY KEY (ASSESSMENT_ID),
    FOREIGN KEY (FORM_ID) REFERENCES FORM(FORM_ID),
    FOREIGN KEY (NURSE_EMPLOYEE_ID) REFERENCES NURSE(NURSE_EMPLOYEE_ID)
);

CREATE TABLE IF NOT EXISTS MEDICATION(
	MED_ID INT,
    MED_NAME VARCHAR(255),
    PRIMARY KEY (MED_ID)
);

CREATE TABLE IF NOT EXISTS NURSE(
	NURSE_EMPLOYEE_ID INT,
    FNAME VARCHAR(255),
    MNAME VARCHAR(255),
    LNAME VARCHAR(255),
    SERVICE_ID INT UNIQUE NOT NULL,
    SSN INT UNIQUE NOT NULL,
    PAYSCALE DECIMAL(2,2),
    SALARY DECIMAL(2,2),
    DNO INT NOT NULL,
    PRIMARY KEY (NURSE_EMPLOYEE_ID),
    FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNO)
);

CREATE TABLE IF NOT EXISTS OTHER_EMPLOYEE(
	OTHER_EMPLOYEE_ID INT,
    FNAME VARCHAR(255),
    MNAME VARCHAR(255),
    LNAME VARCHAR(255),
    PAYSCALE DECIMAL(2,2),
    SALARY DECIMAL(2,2),
    DNO INT NOT NULL,
    PRIMARY KEY (OTHER_EMPLOYEE_ID),
    FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNO)
);

CREATE TABLE IF NOT EXISTS PATIENT (
    PATIENT_ID INT,
    FNAME VARCHAR(255),
    MNAME VARCHAR(255),
    LNAME VARCHAR(255),
    STREET VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    ZIP INT,
    DOB DATE,
    GUARDIAN_ID INT,
    PRIMARY KEY (PATIENT_ID),
    FOREIGN KEY (GUARDIAN_ID) REFERENCES GUARDIAN(GUARDIAN_ID)
);

CREATE TABLE IF NOT EXISTS PATIENT_HAS_EMERGENCY_CONTACT(
	PATIENT_ID INT,
    EMERGENCY_ID INT,
    PRIMARY KEY (PATIENT_ID, EMERGENCY_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
    FOREIGN KEY (EMERGENCY_ID) REFERENCES EMERGENCY_CONTACT(EMERGENCY_ID)
);


CREATE TABLE IF NOT EXISTS PATIENT_PHONE(
PATIENT_ID INT,
PHONE_NUMBER VARCHAR(25),
PRIMARY KEY (PATIENT_ID, PHONE_NUMBER),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);

CREATE TABLE IF NOT EXISTS SERVICE_PROVIDER(
	SERVICE_EMPLOYEE_ID INT,
    FNAME VARCHAR(255),
    MNAME VARCHAR(255),
    LNAME VARCHAR(255),
    SERVICE_ID INT UNIQUE NOT NULL,
    SSN INT UNIQUE NOT NULL,
    PAYSCALE DECIMAL(2,2),
    SALARY DECIMAL(2,2),
    DNO INT NOT NULL,
    PRIMARY KEY (SERVICE_EMPLOYEE_ID),
    FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNO)
);

CREATE TABLE IF NOT EXISTS SYMPTOMS(
	  ASSESSMENT_ID INT,
    SYMPTOM VARCHAR(255),
    PRIMARY KEY (ASSESSMENT_ID, SYMPTOM),
    FOREIGN KEY (ASSESSMENT_ID) REFERENCES INITIAL_ASSESSMENT(ASSESSMENT_ID)
);

CREATE TABLE IF NOT EXISTS TREATMENT (
    TREATMENT_ID INT,
    ICDLOPCS VARCHAR(7),
    TREATMENT_NAME VARCHAR(255),
    COST DECIMAL(2,2),
    PATIENT_ID INT NOT NULL,
    PRIMARY KEY (TREATMENT_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);
